title: UniqueName54321
description: My stuff

remote_theme: daviddarnes/garth

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 5
paginate_path: blog/page:num

collections:
  posts:
    title: Blog
    output: true
    description: "My posts"